fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.default   
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(SENDER_NAME)%'

#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: AppBundle\Entity\User
#    from_email:
#        address: "%mailer_user%"
#        sender_name: "%mailer_user%"
#    registration:
#        confirmation:
#            enabled: true
#            template: FOSUserBundle:Registration:email.txt.twig
#        form:
#            type: AppBundle\Form\RegistrationType
#    profile:
#        form:
#type: AppBundle\Form\ProfileType