fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Customer
    service:
        mailer: mailer # custom mailer service   
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(SENDER_NAME)%'
#    profile:
#        form:
#            type: App\Form\CustomerType
